import theme from 'style/theme';

//  Label Colors
export type LabelColors = keyof typeof theme.color.label;

export const skillsLabel: { [key: string]: LabelColors } = {
  // Language
  Assembly: 'purple',
  C: 'gray',
  CSS: 'blue',
  'C#': 'green',
  'C++': 'navy',
  Dart: 'blue',
  Go: 'blue',
  Haskell: 'gray',
  HTML: 'orange',
  Java: 'darkRed',
  JavaScript: 'yellow',
  Julia: 'purple',
  'Objective-C': 'purple',
  Perl: 'purple',
  PHP: 'purple',
  Python: 'blue',
  R: 'blue',
  Ruby: 'darkRed',
  Rust: 'gray',
  SQL: 'gray',
  Scala: 'darkRed',
  Swift: 'orange',
  TypeScript: 'blue',
  Kotlin: 'orange',
  VBA: 'gray',
  'Visual Basic': 'gray',
  // Front-end
  Apollo: 'purple',
  Angular: 'darkRed',
  jQuery: 'blue',
  MobX: 'orange',
  NextJS: 'gray',
  React: 'blue',
  'React Native': 'blue',
  Redux: 'purple',
  'Sass/SCSS': 'purple',
  Svelte: 'orange',
  Stylus: 'gray',
  Less: 'navy',
  Vue: 'green',
  // Back-end
  '.NET': 'purple',
  'ASP.NET': 'purple',
  Atlas: 'green',
  Django: 'darkGreen',
  Express: 'green',
  Flask: 'gray',
  Gatsby: 'purple',
  Lalavel: 'darkRed',
  Tensorflow: 'orange',
  'Ruby on Rails': 'darkRed',
  NodeJS: 'green',
  NestJS: 'darkRed',
  Spring: 'gray',
  JSP: 'gray',
  JPA: 'gray',
  // Database
  Cassandra: 'blue',
  DynamoDB: 'navy',
  Elasticsearch: 'blue',
  Firebase: 'orange',
  MariaDB: 'brown',
  'Microsoft SQL Server': 'darkRed',
  MongoDB: 'green',
  MySQL: 'gray',
  Oracle: 'darkRed',
  PostgreSQL: 'navy',
  Redis: 'darkRed',
  SQLite: 'navy',
  // Network
  GraphQL: 'purple',
  'REST API': 'gray',
  // Testing
  Jest: 'darkRed',
  Selenium: 'green',
  // ETC
  Amplify: 'orange',
  Apache: 'darkRed',
  'Apache Spark': 'orange',
  Arduino: 'blue',
  AWS: 'orange',
  Azure: 'blue',
  Bitbucket: 'blue',
  Cloudinary: 'blue',
  Cordova: 'gray',
  Docker: 'blue',
  Drupal: 'blue',
  Flutter: 'blue',
  'Facebook Workplace': 'gray',
  Github: 'gray',
  'Github pages': 'gray',
  Gitlab: 'orange',
  'Google Suite': 'blue',
  'Google Cloud Platform': 'blue',
  Hadoop: 'yellow',
  Heroku: 'purple',
  Jira: 'blue',
  Keras: 'darkRed',
  Kubernetes: 'blue',
  Linux: 'yellow',
  'Microsoft Teams': 'purple',
  Netlify: 'blue',
  Pandas: 'blue',
  Puppet: 'orange',
  'Raspberry Pi': 'darkRed',
  Slack: 'purple',
  Symfony: 'gray',
  Torch: 'orange',
  Trello: 'blue',
  Unity: 'gray',
  'Unreal Engine': 'gray',
  Xamarin: 'blue',
  Webpack: 'blue',
  Wordpress: 'blue',
};
